# Runnable entry points.
#
# Split from the checks because they do different things: a check must be
# hermetic and offline, while an app is allowed to touch the network, the git
# index, and a registry token. Keeping them in one file invited confusing one
# for the other.
ctx:

let
  inherit (ctx) pkgs lib has rustInputs kotlinInputs swiftPkgs swiftAvailable commonInputs;

  # Every app operates on the working tree -- regenerating docs/, running
  # cargo, reading spec/ -- so every one of them assumed it was launched from
  # the repository root. `nix run .#docs` from inside docs/ found that out:
  #
  #   /nix/store/...-tabula-docs/bin/tabula-docs: line 14: ./tools/docs:
  #   No such file or directory
  #
  # Prepended to each app rather than fixed in one of them: the bug was in all
  # four, and only the order people happened to run them kept it hidden.
  cdRoot = ''
    if root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
      cd "$root"
    else
      echo "not inside a git checkout of tabula; these apps work on the tree" >&2
      exit 1
    fi
  '';

  app = drv: name: description: {
    type = "app";
    program = "${drv}/bin/${name}";
    meta.description = description;
  };

  conformance = pkgs.writeShellApplication {
    name = "tabula-conformance";
    runtimeInputs = commonInputs ++ [ pkgs.git ] ++ rustInputs
      ++ lib.optionals has.kotlin kotlinInputs
      ++ lib.optionals (has.swift && swiftAvailable) swiftPkgs;
    text = ''
      ${cdRoot}
      ${lib.optionalString has.rustConformance ''
        echo "== rust =="
        ./tools/verify conformance
      ''}
      ${lib.optionalString has.kotlin ''
        echo "== kotlin =="
        ./tools/verify kotlin-conformance
      ''}
      ${lib.optionalString (has.swift && swiftAvailable) ''
        echo "== swift =="
        ./tools/verify swift
      ''}
    '';
  };

  tableDiff = pkgs.writeShellApplication {
    name = "tabula-table-diff";
    runtimeInputs = commonInputs ++ [ pkgs.git ] ++ rustInputs;
    text = ''
      ${cdRoot}
      cd rust
      cargo run -q -p tabula-conformance --bin table-diff --offline --locked -- "$@"
    '';
  };

  # The docs site. `build` regenerates and renders; `serve` also watches.
  #
  # Jekyll is here rather than in a dev shell because it is the only consumer
  # of it in the repository: adding it to the shells would put Ruby on the path
  # of everyone working on Rust.
  docs = pkgs.writeShellApplication {
    name = "tabula-docs";
    runtimeInputs = commonInputs ++ [ pkgs.git pkgs.jekyll ];
    text = ''
      ${cdRoot}
      cmd="''${1:-serve}"

      # Always regenerate first. docs/ is generated from spec/ and serving a
      # stale tree is exactly the failure `tools/verify docs` exists to catch;
      # a preview that shows something the repository does not contain is worse
      # than no preview.
      ./tools/docs

      # The theme is a GitHub Pages built-in and is not in nixpkgs' jekyll, so
      # a local render would die on `theme: jekyll-theme-primer`. Rendering
      # without it is honest about what this is -- a content preview, not a
      # pixel-accurate copy of the published site. The config is overridden
      # rather than edited so docs/_config.yml stays correct for Pages.
      scratch="$(mktemp -d)"
      trap 'rm -rf "$scratch"' EXIT
      grep -v '^theme:' docs/_config.yml > "$scratch/config.yml"

      case "$cmd" in
        build)
          jekyll build --source docs --destination "''${2:-docs/_site}" \
            --config "$scratch/config.yml"
          echo "built into ''${2:-docs/_site}"
          ;;
        serve)
          echo "serving docs/ on http://127.0.0.1:4000 -- content preview;"
          echo "the published site adds the primer theme, which nixpkgs' jekyll lacks."
          jekyll serve --source docs --destination "$scratch/site" \
            --config "$scratch/config.yml" --host 127.0.0.1 --port 4000
          ;;
        *)
          echo "usage: nix run .#docs -- [serve|build [dir]]" >&2
          exit 2
          ;;
      esac
    '';
  };

  # The one command in the repository that is allowed to reach Maven.
  #
  # An app and not a check, for the reason at the top of this file: a check
  # must be hermetic, and this is a bootstrap. It resolves the KSP example
  # against real repositories and writes nix/gradle-lock.json, which is then
  # committed and consumed by nix/gradle-repo.nix as ordinary `fetchurl` calls.
  #
  # After it has run once, `nix flake check` DOES fetch from Maven -- through
  # nix's own downloader, against hashes in the lock. That is Maven wired up
  # through the flake, and it is reproducible in the way the sandbox could
  # never be: same lock, same bytes, every time, on any machine.
  #
  # Run through the flake rather than as a bare script so the gradle, jdk and
  # curl doing the resolving are the pinned ones. A lock generated by whatever
  # gradle happened to be on someone's PATH is a lock nobody can reproduce, and
  # a bootstrap that is not reproducible poisons everything downstream of it --
  # which would be the whole point, missed.
  #
  # Which is also why the shell utilities are listed. `writeShellApplication`
  # PREPENDS runtimeInputs to PATH rather than replacing it, so `find`, `sed`
  # and `diff` would have resolved against whatever the caller had -- and on
  # macOS that is BSD `find` and BSD `sed`, which differ from the GNU ones this
  # was written against. An unpinned tool inside the one command that produces
  # the pin is the same bug one level up.
  #
  # gradle in particular must be the version `kotlin-ksp` replays against:
  # kotlinInputs supplies both, so they cannot drift.
  gradleLock = pkgs.writeShellApplication {
    name = "tabula-gradle-lock";
    runtimeInputs = commonInputs ++ kotlinInputs ++ [
      pkgs.git
      pkgs.curl
      pkgs.coreutils
      pkgs.findutils
      pkgs.gnused
      pkgs.gnugrep
      pkgs.diffutils
    ];
    text = ''
      ${cdRoot}
      ./tools/gradle-lock "$@"
    '';
  };

  verify = pkgs.writeShellApplication {
    name = "tabula-verify";
    runtimeInputs = commonInputs ++ [ pkgs.git ] ++ rustInputs
      ++ lib.optionals has.kotlin kotlinInputs
      ++ lib.optionals (has.swift && swiftAvailable) swiftPkgs;
    text = ''
      ${cdRoot}
      ./tools/verify "$@"
    '';
  };

  publish = import ./publish.nix ctx;

in
{
  conformance = app conformance "tabula-conformance"
    "Run every implementation against spec/conformance";

  table-diff = app tableDiff "tabula-table-diff"
    "Render a machine's matrix as a diffable grid";

  verify = app verify "tabula-verify"
    "Run the same checks nix flake check runs, without the sandbox";

  gradle-lock = app gradleLock "tabula-gradle-lock"
    "Resolve the KSP example against Maven and write nix/gradle-lock.json";

  docs = app docs "tabula-docs"
    "Regenerate docs/ from spec/ and serve it (nix run .#docs -- build)";

  release = app publish.release "tabula-release"
    "Set the version everywhere, verify, and tag";

  publish = app publish.publish "tabula-publish"
    "Publish every language's package (dry run unless --execute)";

  default = app verify "tabula-verify" "Run the checks";
}
