/// Turns a `MachineDesc` into Swift source.
///
/// The shape is fixed by `Sources/TabulaCheck/ReferenceTimer.swift`, which is
/// hand-written and kept building forever. This emitter has to reproduce it,
/// and `codegen-golden/` holds the proof.
public func emit(_ d: MachineDesc) -> String {
    var out = ""
    let mods = d.prototypeModifiers.isEmpty ? "" : d.prototypeModifiers.joined(separator: " ") + " "

    out += "// Generated by tabula. Do not edit.\n"
    out += "//\n"
    out += "// The dispatcher exists ONLY here. A developer never writes a `switch`, so\n"
    out += "// `default:` is not a temptation -- it is not available. That is the\n"
    out += "// difference between a convention and a guarantee.\n"
    out += "import Tabula\n\n"

    // -- cell surface --------------------------------------------------
    out += "/// The cell surface: one required member per non-static cell, with narrowed\n"
    out += "/// argument types.\n"
    out += "///\n"
    out += "/// A protocol, not a base class, because this is what composes: a class\n"
    out += "/// extends one parent, so a base class would cap composition at a single\n"
    out += "/// child. Protocols are Swift's trait bounds.\n"
    let supers = d.children.map { "\($0.alias)Cells" }
    out += "protocol \(d.machine)Cells"
    out += supers.isEmpty ? " {\n" : ": \(supers.joined(separator: ", ")) {\n"

    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            switch c {
            case .handle:
                out += "    \(mods)func \(member(d, i, j))(_ ctx: \(d.ctxType)"
                out += argList(d, i, j)
                out += ") -> Step<\(d.stateType), \(d.effectType)>\n"
            case let .delegate(child):
                guard let ch = d.children.first(where: { $0.alias == child }) else { continue }
                out += "    \(mods)func \(member(d, i, j))ToChild(_ ctx: \(d.ctxType)"
                out += argList(d, i, j)
                out += ") -> \(ch.alias).\(ch.actionType)?\n"
            default:
                break
            }
        }
    }

    // Lens members are per CHILD, not per cell: a second delegate cell to the
    // same child reuses them. Only the action prism above is per cell.
    for ch in d.children {
        out += "\n    // Lens onto `\(ch.alias)`. Per child, not per cell.\n"
        out += "    func \(ch.alias)ChildState(_ s: \(d.stateType)) -> \(ch.alias).\(ch.stateType)\n"
        out += "    func \(ch.alias)Embed(_ s: \(d.stateType), _ child: \(ch.alias).\(ch.stateType)) -> \(d.stateType)\n"
        out += "    func \(ch.alias)Lift(_ effect: \(ch.alias).\(ch.effectType)) -> \(d.effectType)\n"
        out += "    func \(ch.alias)ChildCtx(_ ctx: \(d.ctxType)) -> \(ch.alias).\(ch.ctxType)\n"
    }

    if !d.effects.isEmpty {
        out += "\n    // One required member per effect variant. Add an effect and every\n"
        out += "    // handler stops compiling.\n"
        for e in d.effects {
            out += "    \(mods)func \(lower(e.name))(_ ctx: \(d.ctxType)"
            out += e.hasPayload ? ", _ effect: \(d.effectType).\(e.name)" : ""
            out += ") -> \(d.actionType)?\n"
        }
    }
    out += "}\n\n"

    // -- dispatcher ----------------------------------------------------
    out += "/// Dispatch one `(state, action)` pair. No `default:` branch.\n"
    out += "\(mods)func step(_ cells: \(d.machine)Cells, _ ctx: \(d.ctxType), "
    out += "_ s: \(d.stateType), _ a: \(d.actionType)) -> Step<\(d.stateType), \(d.effectType)> {\n"
    out += "    switch (s, a) {\n"
    for (i, row) in d.rows.enumerated() {
        for (j, _) in row.enumerated() {
            out += "    case \(pattern(d, i, j)):\n"
            out += "        return \(arm(d, i, j))\n"
        }
    }
    out += "    }\n}\n"

    // -- effect dispatch -----------------------------------------------
    if !d.effects.isEmpty {
        out += "\n/// Carry out one effect, returning any follow-up action.\n"
        out += "\(mods)func perform(_ cells: \(d.machine)Cells, _ ctx: \(d.ctxType), "
        out += "_ f: \(d.effectType)) -> \(d.actionType)? {\n"
        out += "    switch f {\n"
        for e in d.effects {
            out += e.hasPayload
                ? "    case let .\(lower(e.name))(payload):\n        return cells.\(lower(e.name))(ctx, payload)\n"
                : "    case .\(lower(e.name)):\n        return cells.\(lower(e.name))(ctx)\n"
        }
        out += "    }\n}\n"
    }

    // -- table ----------------------------------------------------------
    out += "\n/// The matrix as inert data. Diagrams, lints, and coverage read this.\n"
    out += "let TABLE = Table(\n"
    out += "    machine: \(q(d.machine)),\n"
    out += "    states: [\(d.states.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "    actions: [\(d.actions.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "    cells: [\n"
    for row in d.rows {
        out += "        [\(row.map(cellData).joined(separator: ", "))],\n"
    }
    out += "    ],\n"
    out += "    initial: \(q(d.initial))\n"
    out += ")\n"

    // -- payloads --------------------------------------------------------
    out += "\n/// State payload fields, as `(state, field, type)`.\n"
    let entries = d.states.flatMap { v in v.fields.map { (v.name, $0.name, $0.type) } }
    if entries.isEmpty {
        out += "let PAYLOADS: Payloads = []\n"
    } else {
        out += "let PAYLOADS: Payloads = [\n"
        for e in entries {
            out += "    (state: \(q(e.0)), field: \(q(e.1)), type: \(q(e.2))),\n"
        }
        out += "]\n"
    }
    return out
}

/// Cell member name: `Idle` x `Start` becomes `idleStart`.
///
/// Swift macros can build identifiers, so Swift names cells — the same choice
/// Kotlin makes, and the opposite of Rust, where `macro_rules!` cannot.
private func member(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    lower(d.states[i].name) + cap(d.actions[j].name)
}

/// Narrowed arguments, only for variants that carry a payload.
private func argList(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    var s = ""
    if d.states[i].hasPayload { s += ", _ state: \(d.states[i].name)" }
    if d.actions[j].hasPayload { s += ", _ action: \(d.actions[j].name)" }
    return s
}

private func pattern(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    let sp = d.states[i].hasPayload
    let ap = d.actions[j].hasPayload
    let s = lower(d.states[i].name)
    let a = lower(d.actions[j].name)
    switch (sp, ap) {
    case (false, false): return "(.\(s), .\(a))"
    case (true, false): return "(.\(s), .\(a))"
    case (false, true): return "(.\(s), .\(a))"
    case (true, true): return "(.\(s), .\(a))"
    }
}

private func arm(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    switch d.rows[i][j] {
    case .ignore:
        return ".ignored"
    case .handle:
        var call = "cells.\(member(d, i, j))(ctx"
        if d.states[i].hasPayload { call += ", narrow(s)" }
        if d.actions[j].hasPayload { call += ", narrow(a)" }
        return call + ")"
    case .unreachable:
        return "fatalError(\(q("tabula: \(d.states[i].name) x \(d.actions[j].name) was declared UNREACHABLE but occurred")))"
    case let .go(target, args, effects):
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".go(.\(lower(target))\(args), effects: [\(e)])"
    case let .emit(effects):
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".stay(effects: [\(e)])"
    case let .delegate(child):
        return "delegateTo\(cap(child))(cells, ctx, s, cells.\(member(d, i, j))ToChild(ctx))"
    }
}

private func cellData(_ c: CellDesc) -> String {
    switch c {
    case .ignore: return ".ignore"
    case .handle: return ".handle"
    case .unreachable: return ".unreachable"
    case let .go(target, _, effects):
        return ".go(target: \(q(target)), effects: [\(effects.map(q).joined(separator: ", "))])"
    case let .emit(effects):
        return ".emit(effects: [\(effects.map(q).joined(separator: ", "))])"
    case let .delegate(child):
        return ".delegate(child: \(q(child)))"
    }
}

private func q(_ s: String) -> String { "\"\(s)\"" }
private func lower(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).lowercased() + s.dropFirst() }
private func cap(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).uppercased() + s.dropFirst() }
