/// Turns a `MachineDesc` into Swift source.
///
/// The shape is fixed by `Sources/TabulaCheck/ReferenceTimer.swift`, which is
/// hand-written and kept building forever. This emitter has to reproduce it,
/// `codegen-golden/` pins what it produces, and `tools/verify swift-codegen`
/// compiles that output against `codegen-support/` -- a golden alone proves
/// only determinism, not that the output is Swift.
public func emit(_ d: MachineDesc) -> String {
    let color = Color(d.prototypeModifiers)
    var out = ""

    out += "// Generated by tabula. Do not edit.\n"
    out += "//\n"
    out += "// The dispatcher exists ONLY here. A developer never writes a `switch`, so\n"
    out += "// `default:` is not a temptation -- it is not available. That is the\n"
    out += "// difference between a convention and a guarantee.\n"
    out += "import Tabula\n\n"

    // -- refusals ------------------------------------------------------
    //
    // What this emitter cannot produce correctly, it refuses at the top of the
    // file, in the user's build, naming the variant. The alternative is source
    // that fails to compile somewhere in the middle, with a message about
    // generated code the user never wrote.
    for line in refusals(d) {
        out += "#error(\(q(line)))\n"
    }

    // -- cell surface --------------------------------------------------
    out += "/// The cell surface: one required member per non-static cell, with narrowed\n"
    out += "/// argument types.\n"
    out += "///\n"
    out += "/// A protocol, not a base class, because this is what composes: a class\n"
    out += "/// extends one parent, so a base class would cap composition at a single\n"
    out += "/// child. Protocols are Swift's trait bounds.\n"
    let supers = d.children.map { "\($0.alias)Cells" }
    out += "protocol \(d.machine)Cells"
    out += supers.isEmpty ? " {\n" : ": \(supers.joined(separator: ", ")) {\n"

    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            switch c {
            case .handle:
                out += "    \(color.prefix)func \(member(d, i, j))(_ ctx: \(d.ctxType)"
                out += argList(d, i, j)
                out += ")\(color.suffix) -> Step<\(d.stateType), \(d.effectType)>\n"
            case let .delegate(child):
                guard let ch = d.children.first(where: { $0.alias == child }) else { continue }
                out += "    \(color.prefix)func \(member(d, i, j))ToChild(_ ctx: \(d.ctxType)"
                out += argList(d, i, j)
                out += ")\(color.suffix) -> \(ch.alias).\(ch.actionType)?\n"
            default:
                break
            }
        }
    }

    // Lens members are per CHILD, not per cell: a second delegate cell to the
    // same child reuses them. Only the action prism above is per cell.
    for ch in d.children {
        out += "\n    // Lens onto `\(ch.alias)`. Per child, not per cell.\n"
        out += "    func \(ch.alias)ChildState(_ s: \(d.stateType)) -> \(ch.alias).\(ch.stateType)\n"
        out += "    func \(ch.alias)Embed(_ s: \(d.stateType), _ child: \(ch.alias).\(ch.stateType)) -> \(d.stateType)\n"
        out += "    func \(ch.alias)Lift(_ effect: \(ch.alias).\(ch.effectType)) -> \(d.effectType)\n"
        out += "    func \(ch.alias)ChildCtx(_ ctx: \(d.ctxType)) -> \(ch.alias).\(ch.ctxType)\n"
    }

    if !d.effects.isEmpty {
        out += "\n    // One required member per effect variant. Add an effect and every\n"
        out += "    // handler stops compiling.\n"
        for e in d.effects {
            out += "    \(color.prefix)func \(lower(e.name))(_ ctx: \(d.ctxType)"
            out += effectParam(e)
            out += ")\(color.suffix) -> \(d.actionType)?\n"
        }
    }
    out += "}\n\n"

    // -- dispatcher ----------------------------------------------------
    //
    // Only HANDLE arms bind payloads, because only they hand the payload on.
    // Every other arm matches the bare case, which Swift allows for a case
    // with associated values -- and which leaves no unused bindings behind.
    out += "/// Dispatch one `(state, action)` pair. No `default:` branch.\n"
    out += "\(color.prefix)func step(_ cells: \(d.machine)Cells, _ ctx: \(d.ctxType), "
    out += "_ s: \(d.stateType), _ a: \(d.actionType))\(color.suffix) -> Step<\(d.stateType), \(d.effectType)> {\n"
    out += "    switch (s, a) {\n"
    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            if case .handle = c {
                let sb = bind(d.states[i], side: "s", avoid: reserved)
                let ab = bind(d.actions[j], side: "a", avoid: reserved.union(sb.names))
                let binds = !sb.names.isEmpty || !ab.names.isEmpty
                out += "    case \(binds ? "let " : "")(\(sb.pattern), \(ab.pattern)):\n"
                var call = "cells.\(member(d, i, j))(ctx"
                if d.states[i].hasPayload { call += ", \(sb.value)" }
                if d.actions[j].hasPayload { call += ", \(ab.value)" }
                out += "        return \(color.call)\(call))\n"
            } else {
                out += "    case (.\(lower(d.states[i].name)), .\(lower(d.actions[j].name))):\n"
                out += "        return \(arm(d, i, j, color))\n"
            }
        }
    }
    out += "    }\n}\n"

    // -- effect dispatch -----------------------------------------------
    if !d.effects.isEmpty {
        out += "\n/// Carry out one effect, returning any follow-up action.\n"
        out += "\(color.prefix)func perform(_ cells: \(d.machine)Cells, _ ctx: \(d.ctxType), "
        out += "_ f: \(d.effectType))\(color.suffix) -> \(d.actionType)? {\n"
        out += "    switch f {\n"
        for e in d.effects {
            let b = bind(e, side: "e", avoid: ["cells", "ctx", "f"])
            if b.names.isEmpty {
                out += "    case .\(lower(e.name)):\n"
                out += "        return \(color.call)cells.\(lower(e.name))(ctx)\n"
            } else {
                // One field passes its value, as `ReferenceTimer` passes a
                // `Reason`; several pass a labelled tuple.
                let arg = b.names.count == 1
                    ? b.names[0]
                    : "(" + zip(e.fields, b.names).map { f, n in
                        f.name.isEmpty ? n : "\(f.name): \(n)"
                    }.joined(separator: ", ") + ")"
                out += "    case let \(b.pattern):\n"
                out += "        return \(color.call)cells.\(lower(e.name))(ctx, \(arg))\n"
            }
        }
        out += "    }\n}\n"
    }

    // -- table ----------------------------------------------------------
    out += "\n/// The matrix as inert data. Diagrams, lints, and coverage read this.\n"
    out += "let TABLE = Table(\n"
    out += "    machine: \(q(d.machine)),\n"
    out += "    states: [\(d.states.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "    actions: [\(d.actions.map { q($0.name) }.joined(separator: ", "))],\n"
    out += "    cells: [\n"
    for row in d.rows {
        out += "        [\(row.map(cellData).joined(separator: ", "))],\n"
    }
    out += "    ],\n"
    out += "    initial: \(q(d.initial))\n"
    out += ")\n"

    // -- payloads --------------------------------------------------------
    out += "\n/// State payload fields, as `(state, field, type)`.\n"
    let entries = d.states.flatMap { v in v.fields.map { (v.name, $0.name, $0.type) } }
    if entries.isEmpty {
        out += "let PAYLOADS: Payloads = []\n"
    } else {
        out += "let PAYLOADS: Payloads = [\n"
        for e in entries {
            out += "    (state: \(q(e.0)), field: \(q(e.1)), type: \(q(e.2))),\n"
        }
        out += "]\n"
    }
    return out
}

/// The prototype's modifiers, split by where Swift wants them.
///
/// `MachineSyntax` records attributes, modifiers and effect specifiers in one
/// list, in source order, and copies them verbatim (ARCHITECTURE 5). Verbatim
/// is right; *one place* is not. `@MainActor` goes before `func`, while `async`
/// and `throws` go after the parameter list -- and every call into a colored
/// member needs `try` / `await`, which is how the color reaches the caller.
private struct Color {
    /// Attributes and modifiers: `@MainActor `, `nonisolated `.
    let prefix: String
    /// Effect specifiers, after the parameters: ` async throws`.
    let suffix: String
    /// What a call into a member of this color needs: `try await `.
    let call: String

    init(_ mods: [String]) {
        let specifiers: Set<String> = ["async", "throws", "rethrows"]
        let before = mods.filter { !specifiers.contains($0) }
        let after = mods.filter { specifiers.contains($0) }
        prefix = before.isEmpty ? "" : before.joined(separator: " ") + " "
        suffix = after.isEmpty ? "" : " " + after.joined(separator: " ")
        let throwing = after.contains("throws") || after.contains("rethrows")
        call = (throwing ? "try " : "") + (after.contains("async") ? "await " : "")
    }
}

/// The dispatcher's own parameter names. A payload field bound under one of
/// these would shadow it, and `cells.idleStart(ctx, ...)` would quietly pass
/// the field instead of the context.
private let reserved: Set<String> = ["cells", "ctx", "s", "a"]

/// A pattern binding a variant's payload, and the narrowed value built from it.
///
/// `Running(since: Int)` binds as `.running(since)` and constructs
/// `Running(since: since)` -- the narrowed struct `ReferenceTimer.swift`
/// declares beside the enum. An unlabelled field binds positionally
/// (`s0`, `a0`) and constructs without a label.
private func bind(_ v: Variant, side: String, avoid: Set<String>)
    -> (pattern: String, value: String, names: [String])
{
    let base = ".\(lower(v.name))"
    guard v.hasPayload, !v.fields.isEmpty else { return (base, "\(v.name)()", []) }
    var taken = avoid
    var names: [String] = []
    for (k, f) in v.fields.enumerated() {
        var n = f.name.isEmpty ? "\(side)\(k)" : f.name
        if taken.contains(n) { n = side + cap(n) }
        taken.insert(n)
        names.append(n)
    }
    let labelled = zip(v.fields, names).map { f, n in f.name.isEmpty ? n : "\(f.name): \(n)" }
    return (
        "\(base)(\(names.joined(separator: ", ")))",
        "\(v.name)(\(labelled.joined(separator: ", ")))",
        names
    )
}

/// The effect handler's payload parameter: the value for one field, a
/// labelled tuple for several, nothing for none.
private func effectParam(_ e: Variant) -> String {
    guard e.hasPayload, !e.fields.isEmpty else { return "" }
    if e.fields.count == 1 { return ", _ effect: \(e.fields[0].type)" }
    let parts = e.fields.map { $0.name.isEmpty ? $0.type : "\($0.name): \($0.type)" }
    return ", _ effect: (\(parts.joined(separator: ", ")))"
}

/// Everything this emitter knows it cannot produce, as `#error` messages.
private func refusals(_ d: MachineDesc) -> [String] {
    var out: [String] = []
    // `Variant.fields` may be empty with `hasPayload` true: a generator that
    // cannot resolve a type still gets its lints. It cannot get a binding.
    for v in d.states + d.actions + d.effects where v.hasPayload && v.fields.isEmpty {
        out.append("tabula: the payload fields of `\(v.name)` are unknown, so the generator cannot bind them")
    }
    // A GO or EMIT names effects, and the model carries no arguments for one.
    // `.stopClock` for `stopClock(reason:)` is not a value.
    let payloaded = Set(d.effects.filter { $0.hasPayload }.map(\.name))
    for (i, row) in d.rows.enumerated() {
        for (j, c) in row.enumerated() {
            let named: [String]
            switch c {
            case let .go(_, _, effects): named = effects
            case let .emit(effects): named = effects
            default: named = []
            }
            for e in named where payloaded.contains(e) {
                out.append(
                    "tabula: cell (\(d.states[i].name), \(d.actions[j].name)) emits `\(e)`, which carries "
                        + "a payload; GO and EMIT cannot supply one yet. Use HANDLE.")
            }
        }
    }
    return out
}

/// Cell member name: `Idle` x `Start` becomes `idleStart`.
///
/// Swift macros can build identifiers, so Swift names cells — the same choice
/// Kotlin makes, and the opposite of Rust, where `macro_rules!` cannot.
private func member(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    lower(d.states[i].name) + cap(d.actions[j].name)
}

/// Narrowed arguments, only for variants that carry a payload.
private func argList(_ d: MachineDesc, _ i: Int, _ j: Int) -> String {
    var s = ""
    if d.states[i].hasPayload { s += ", _ state: \(d.states[i].name)" }
    if d.actions[j].hasPayload { s += ", _ action: \(d.actions[j].name)" }
    return s
}

/// Every arm but HANDLE, which binds and is written by the dispatcher itself.
private func arm(_ d: MachineDesc, _ i: Int, _ j: Int, _ color: Color) -> String {
    switch d.rows[i][j] {
    case .ignore, .handle:
        return ".ignored"
    case .unreachable:
        return "fatalError(\(q("tabula: \(d.states[i].name) x \(d.actions[j].name) was declared UNREACHABLE but occurred")))"
    case let .go(target, args, effects):
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".go(.\(lower(target))\(args), effects: [\(e)])"
    case let .emit(effects):
        let e = effects.map { ".\(lower($0))" }.joined(separator: ", ")
        return ".stay(effects: [\(e)])"
    case let .delegate(child):
        // `delegateTo<Child>` is not emitted yet; see PLAN, September 2026
        // audit. The call is here so the gap is a compile error naming it.
        return "\(color.call)delegateTo\(cap(child))(cells, ctx, s, \(color.call)cells.\(member(d, i, j))ToChild(ctx))"
    }
}

private func cellData(_ c: CellDesc) -> String {
    switch c {
    case .ignore: return ".ignore"
    case .handle: return ".handle"
    case .unreachable: return ".unreachable"
    case let .go(target, _, effects):
        return ".go(target: \(q(target)), effects: [\(effects.map(q).joined(separator: ", "))])"
    case let .emit(effects):
        return ".emit(effects: [\(effects.map(q).joined(separator: ", "))])"
    case let .delegate(child):
        return ".delegate(child: \(q(child)))"
    }
}

private func q(_ s: String) -> String { "\"\(s)\"" }
private func lower(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).lowercased() + s.dropFirst() }
private func cap(_ s: String) -> String { s.isEmpty ? s : s.prefix(1).uppercased() + s.dropFirst() }
