//! Adapter for `spec/conformance/payload-hoist.tbl`.
//!
//! The only coverage for `tabula::payload-hoist`, and the only fixture whose
//! point is a *warning* rather than a behaviour.
//!
//! `attempt` lives in three states. Three is `PAYLOAD_HOIST_STATES` exactly,
//! so an implementation that fired on `>` rather than `>=` would pass every
//! other fixture and fail this one — which is the whole reason the machine is
//! shaped this way rather than with four.
//!
//! `PAYLOADS` is emitted by the macro from the `states` block below, so this
//! file never spells the field list twice. The type it records is `u32`;
//! Kotlin's adapter records `Long` and Swift's `Int`, and
//! `tabula::lint::canonical_type` maps all three onto `int` before the
//! comparison. That is what lets one `.lint` golden be shared — see
//! `spec/diagnostics.md`.

use std::collections::BTreeMap;

use tabula::{transition_matrix, Handle, Outcome, Step};

use super::{Adapter, Observed};
use crate::{Expect, Spec, Trace};

#[derive(Debug, Default)]
pub struct Ctx {
    pub max_attempts: u32,
}

transition_matrix! {
    machine Conn;
    context Ctx;
    state   State;
    action  Action;
    effects Effect { }
    initial Connecting;

    states  { Connecting { attempt: u32 }, Backoff { attempt: u32 },
              Reconnecting { attempt: u32 }, Live }
    actions { Open, Fail, Timeout }

    //                    Open     Fail                            Timeout
    Connecting   => [     HANDLE,  GO!(Backoff { attempt: 0 }),      GO!(Backoff { attempt: 0 })  ];
    Backoff      => [     IGNORE,  IGNORE,                           HANDLE                       ];
    Reconnecting => [     HANDLE,  GO!(Backoff { attempt: 0 }),      GO!(Backoff { attempt: 0 })  ];
    Live         => [     IGNORE,  GO!(Reconnecting { attempt: 0 }), IGNORE                       ];
}

// `Cells` is generated by the macro as the bundled bound trait, so the
// implementing type needs another name. Each machine gets its own module.
struct Impl;

impl Handle<Conn, Connecting, Open> for Impl {
    fn handle(&mut self, _c: &mut Ctx, _s: Connecting, _a: Open) -> Step<State, Effect> {
        Step::go(State::Live(Live))
    }
}

impl Handle<Conn, Reconnecting, Open> for Impl {
    fn handle(&mut self, _c: &mut Ctx, _s: Reconnecting, _a: Open) -> Step<State, Effect> {
        Step::go(State::Live(Live))
    }
}

/// The only cell that advances the counter, and the only one that can: the
/// `GO!` cells into `Backoff` are static, and a static cell cannot read the
/// state it is leaving, so each of them restarts the count at zero. That is
/// half of why this machine wants the field in `Ctx`.
impl Handle<Conn, Backoff, Timeout> for Impl {
    fn handle(&mut self, c: &mut Ctx, s: Backoff, _a: Timeout) -> Step<State, Effect> {
        if s.attempt >= c.max_attempts {
            Step::stay()
        } else {
            Step::go(State::Reconnecting(Reconnecting {
                attempt: s.attempt + 1,
            }))
        }
    }
}

pub struct PayloadHoistAdapter;

fn state_from(name: &str, f: &BTreeMap<String, i64>) -> Result<State, String> {
    let attempt = f.get("attempt").copied().unwrap_or(0) as u32;
    Ok(match name {
        "Connecting" => State::Connecting(Connecting { attempt }),
        "Backoff" => State::Backoff(Backoff { attempt }),
        "Reconnecting" => State::Reconnecting(Reconnecting { attempt }),
        "Live" => State::Live(Live),
        _ => return Err(format!("payload-hoist: unknown state `{name}`")),
    })
}

fn action_from(name: &str) -> Result<Action, String> {
    Ok(match name {
        "Open" => Action::Open(Open),
        "Fail" => Action::Fail(Fail),
        "Timeout" => Action::Timeout(Timeout),
        _ => return Err(format!("payload-hoist: unknown action `{name}`")),
    })
}

/// Render a state back into fixture vocabulary: variant name plus the fields
/// the trace chose to assert on.
fn describe(s: State, want: &BTreeMap<String, i64>) -> (String, BTreeMap<String, i64>) {
    let (name, attempt) = match s {
        State::Connecting(v) => ("Connecting", Some(v.attempt)),
        State::Backoff(v) => ("Backoff", Some(v.attempt)),
        State::Reconnecting(v) => ("Reconnecting", Some(v.attempt)),
        State::Live(_) => ("Live", None),
    };
    let mut fields = BTreeMap::new();
    // `filter` rather than nested `if`s: clippy reads the nested form as
    // collapsible and the collapsed form does not type-check, which is a
    // round trip worth skipping.
    if let Some(a) = attempt.filter(|_| want.contains_key("attempt")) {
        fields.insert("attempt".to_string(), a as i64);
    }
    (name.to_string(), fields)
}

impl Adapter for PayloadHoistAdapter {
    fn name(&self) -> &'static str {
        "payload-hoist"
    }

    fn check_table(&self, spec: &Spec) -> Vec<String> {
        crate::check_table(&TABLE, spec)
    }

    fn grid(&self) -> String {
        tabula::export::to_grid(&TABLE)
    }

    fn lint(&self) -> String {
        tabula::lint::report_with_payloads(&TABLE, PAYLOADS)
    }

    fn coverage_report(&self) -> String {
        tabula::export::to_coverage_report(&TABLE)
    }

    fn replay(&self, trace: &Trace) -> Result<Vec<Observed>, String> {
        let mut ctx = Ctx {
            max_attempts: trace.ctx.get("max_attempts").copied().unwrap_or(0) as u32,
        };
        let mut cells = Impl;
        let mut state = state_from(&trace.from, &trace.from_fields)?;
        let mut out = vec![];

        for st in &trace.steps {
            let action = action_from(&st.action)?;
            let step = step(&mut cells, &mut ctx, state, action);

            let effects = step.effects.iter().map(|e| format!("{e:?}")).collect();
            let expect = match step.outcome {
                Outcome::Stay => Expect::Stay,
                Outcome::Ignored => Expect::Ignored,
                Outcome::Go(next) => {
                    state = next;
                    let want = match &st.expect {
                        Expect::Go { fields, .. } => fields.clone(),
                        _ => BTreeMap::new(),
                    };
                    let (name, fields) = describe(next, &want);
                    Expect::Go {
                        state: name,
                        fields,
                    }
                }
            };
            out.push(Observed { expect, effects });
        }
        Ok(out)
    }
}
