stateDiagram-v2
    [*] --> Connecting
    Connecting --> Connecting: Open / ?handle
    Connecting --> Backoff: Fail
    Connecting --> Backoff: Timeout
    Backoff --> Backoff: Timeout / ?handle
    Reconnecting --> Reconnecting: Open / ?handle
    Reconnecting --> Backoff: Fail
    Reconnecting --> Backoff: Timeout
    Live --> Reconnecting: Fail
