package codegen

/**
 * Turns a [MachineDesc] into Kotlin source.
 *
 * The shape is fixed by `test/ReferenceTimer.kt` and `test/Composition.kt`.
 * Those files are hand-written and kept building forever; this emitter has to
 * reproduce them, and `codegen/golden/` holds the proof.
 */
fun emit(d: MachineDesc): String = buildString {
    val mods = if (d.prototypeModifiers.isEmpty()) "" else d.prototypeModifiers.joinToString(" ") + " "

    appendLine("// Generated by tabula. Do not edit.")
    appendLine("//")
    appendLine("// The dispatcher exists ONLY here. A developer never writes a `when`, so")
    appendLine("// `else` is not a temptation -- it is not available. That is the difference")
    appendLine("// between a convention and a guarantee.")
    appendLine("package ${d.packageName}")
    appendLine()
    appendLine("import dev.tabula.Cell")
    appendLine("import dev.tabula.Step")
    appendLine("import dev.tabula.Table")
    appendLine()

    // -- cell surface --------------------------------------------------
    appendLine("/**")
    appendLine(" * The cell surface: one required member per non-static cell, with narrowed")
    appendLine(" * argument types.")
    appendLine(" *")
    appendLine(" * An interface, not abstract members on a class, because this is what")
    appendLine(" * composes: a class extends one parent, so abstract members would cap")
    appendLine(" * composition at a single child. Interfaces are Kotlin's trait bounds.")
    appendLine(" */")
    val supers = d.children.joinToString("") { " ${it.alias}.Cells," }
    appendLine("interface Cells${if (supers.isEmpty()) "" else " :${supers.dropLast(1)}"} {")

    forEachCell(d) { i, j, cell ->
        when (cell) {
            is CellDesc.Handle -> appendLine(
                "    ${mods}fun ${member(d, i, j)}(ctx: ${d.ctxType}, " +
                    "state: ${d.stateType}.${d.states[i].name}, " +
                    "action: ${d.actionType}.${d.actions[j].name}): Step<${d.stateType}, ${d.effectType}>"
            )
            is CellDesc.Delegate -> {
                val c = child(d, cell.child)
                appendLine(
                    "    ${mods}fun ${member(d, i, j)}ToChild(ctx: ${d.ctxType}, " +
                        "state: ${d.stateType}.${d.states[i].name}, " +
                        "action: ${d.actionType}.${d.actions[j].name}): ${c.alias}.${c.actionType}?"
                )
            }
            else -> {}
        }
    }

    // Lens members are per CHILD, not per cell: a second delegate cell to the
    // same child reuses them. Only the action prism above is per cell.
    for (c in d.children) {
        appendLine()
        appendLine("    // Lens onto `${c.alias}`. Per child, not per cell.")
        appendLine("    fun ${c.alias}ChildState(state: ${d.stateType}): ${c.alias}.${c.stateType}")
        appendLine("    fun ${c.alias}Embed(state: ${d.stateType}, child: ${c.alias}.${c.stateType}): ${d.stateType}")
        appendLine("    fun ${c.alias}Lift(effect: ${c.alias}.${c.effectType}): ${d.effectType}")
        appendLine("    fun ${c.alias}ChildCtx(ctx: ${d.ctxType}): ${c.alias}.${c.ctxType}")
    }

    if (d.effects.isNotEmpty()) {
        appendLine()
        appendLine("    // One required member per effect variant. Add an effect and every")
        appendLine("    // handler stops compiling.")
        for (e in d.effects) {
            appendLine(
                "    ${mods}fun ${lower(e.name)}(ctx: ${d.ctxType}, " +
                    "effect: ${d.effectType}.${e.name}): ${d.actionType}?"
            )
        }
    }
    appendLine("}")
    appendLine()

    // -- dispatcher ----------------------------------------------------
    appendLine("/** Dispatch one `(state, action)` pair. No wildcard branch. */")
    appendLine(
        "${mods}fun step(cells: Cells, ctx: ${d.ctxType}, s: ${d.stateType}, a: ${d.actionType}): " +
            "Step<${d.stateType}, ${d.effectType}> = when (s) {"
    )
    d.states.forEachIndexed { i, state ->
        appendLine("    is ${d.stateType}.${state.name} -> when (a) {")
        d.actions.forEachIndexed { j, action ->
            appendLine("        is ${d.actionType}.${action.name} -> ${arm(d, i, j)}")
        }
        appendLine("    }")
    }
    appendLine("}")

    // -- delegate helpers ----------------------------------------------
    for (c in d.children) {
        appendLine()
        appendLine("/**")
        appendLine(" * Run `${c.alias}` and fold the result back through the lens.")
        appendLine(" *")
        appendLine(" * A null child action reports **Ignored**, not Stay: a parent action the")
        appendLine(" * child's alphabet does not contain was not handled.")
        appendLine(" */")
        appendLine(
            "private ${mods}fun delegateTo${cap(c.alias)}(cells: Cells, ctx: ${d.ctxType}, " +
                "s: ${d.stateType}, childAction: ${c.alias}.${c.actionType}?): " +
                "Step<${d.stateType}, ${d.effectType}> {"
        )
        appendLine("    if (childAction == null) return Step.Ignored")
        appendLine("    val childStep = ${c.alias}.step(")
        appendLine("        cells, cells.${c.alias}ChildCtx(ctx), cells.${c.alias}ChildState(s), childAction,")
        appendLine("    )")
        appendLine("    val effects = childStep.effects.map(cells::${c.alias}Lift)")
        appendLine("    return when (childStep) {")
        appendLine("        is Step.Go -> Step.Go(cells.${c.alias}Embed(s, childStep.next), effects)")
        appendLine("        is Step.Stay -> Step.Stay(effects)")
        appendLine("        is Step.Ignored -> Step.Ignored")
        appendLine("    }")
        appendLine("}")
    }

    // -- effect dispatch -----------------------------------------------
    if (d.effects.isNotEmpty()) {
        appendLine()
        appendLine("/** Carry out one effect, returning any follow-up action. */")
        appendLine(
            "${mods}fun perform(cells: Cells, ctx: ${d.ctxType}, f: ${d.effectType}): " +
                "${d.actionType}? = when (f) {"
        )
        for (e in d.effects) {
            appendLine("    is ${d.effectType}.${e.name} -> cells.${lower(e.name)}(ctx, f)")
        }
        appendLine("}")
    }

    // -- table ----------------------------------------------------------
    appendLine()
    appendLine("/** The matrix as inert data. Diagrams, lints, and coverage read this. */")
    appendLine("val TABLE = Table(")
    appendLine("    machine = ${q(d.machine)},")
    appendLine("    states = listOf(${d.states.joinToString(", ") { q(it.name) }}),")
    appendLine("    actions = listOf(${d.actions.joinToString(", ") { q(it.name) }}),")
    appendLine("    initial = ${q(d.initial)},")
    appendLine("    cells = listOf(")
    d.rows.forEach { row ->
        appendLine("        listOf(${row.joinToString(", ") { cellData(it) }}),")
    }
    appendLine("    ),")
    appendLine(")")
}

private inline fun forEachCell(d: MachineDesc, body: (Int, Int, CellDesc) -> Unit) {
    d.rows.forEachIndexed { i, row -> row.forEachIndexed { j, c -> body(i, j, c) } }
}

private fun child(d: MachineDesc, alias: String): ChildDesc =
    d.children.firstOrNull { it.alias == alias }
        ?: error("tabula::unknown-child: `$alias` is not a declared child")

/**
 * Cell member name: `Idle` x `Start` becomes `idleStart`.
 *
 * KSP can build identifiers, which is why Kotlin names cells and Rust reaches
 * for trait bounds instead. See ARCHITECTURE §11.0.
 */
private fun member(d: MachineDesc, i: Int, j: Int): String =
    lower(d.states[i].name) + cap(d.actions[j].name)

private fun arm(d: MachineDesc, i: Int, j: Int): String {
    val bind = if (d.states[i].hasPayload || d.actions[j].hasPayload) "s, a" else "s, a"
    return when (val c = d.rows[i][j]) {
        is CellDesc.Ignore -> "Step.Ignored"
        is CellDesc.Handle -> "cells.${member(d, i, j)}(ctx, $bind)"
        is CellDesc.Unreachable ->
            "error(${q("tabula: ${d.states[i].name} x ${d.actions[j].name} was declared UNREACHABLE but occurred")})"
        is CellDesc.Go -> {
            val target = "${d.stateType}.${c.target}${c.targetArgs}"
            if (c.effects.isEmpty()) "Step.Go($target)"
            else "Step.Go($target, listOf(${c.effects.joinToString(", ") { "${d.effectType}.$it" }}))"
        }
        is CellDesc.Emit ->
            "Step.Stay(listOf(${c.effects.joinToString(", ") { "${d.effectType}.$it" }}))"
        is CellDesc.Delegate ->
            "delegateTo${cap(c.child)}(cells, ctx, s, cells.${member(d, i, j)}ToChild(ctx, s, a))"
    }
}

private fun cellData(c: CellDesc): String = when (c) {
    is CellDesc.Ignore -> "Cell.Ignore"
    is CellDesc.Handle -> "Cell.Handle"
    is CellDesc.Unreachable -> "Cell.Unreachable"
    is CellDesc.Go ->
        if (c.effects.isEmpty()) "Cell.Go(${q(c.target)})"
        else "Cell.Go(${q(c.target)}, listOf(${c.effects.joinToString(", ") { q(it) }}))"
    is CellDesc.Emit -> "Cell.Emit(listOf(${c.effects.joinToString(", ") { q(it) }}))"
    is CellDesc.Delegate -> "Cell.Delegate(${q(c.child)})"
}

private fun q(s: String) = "\"$s\""
private fun lower(s: String) = s.replaceFirstChar { it.lowercase() }
private fun cap(s: String) = s.replaceFirstChar { it.uppercase() }
