// Turns a [MachineDesc] into Kotlin source.
//
// The shape is fixed by `test/ReferenceTimer.kt` and `test/Composition.kt`.
// Those files are hand-written and kept building forever; this emitter has to
// reproduce them, and `tools/verify kotlin-codegen` holds the proof by
// compiling what it emits against `codegen/support/`.
package center.tabula.codegen

fun emit(d: MachineDesc): String = buildString {
    val mods = if (d.prototypeModifiers.isEmpty()) "" else d.prototypeModifiers.joinToString(" ") + " "
    val vis = if (d.visibility.isEmpty()) "" else d.visibility + " "
    val recv = if (d.prototypeReceiver.isEmpty()) "" else d.prototypeReceiver + "."

    appendLine("// Generated by tabular-center. Do not edit.")
    appendLine("//")
    appendLine("// The dispatcher exists ONLY here. A developer never writes a `when`, so")
    appendLine("// `else` is not a temptation -- it is not available. That is the difference")
    appendLine("// between a convention and a guarantee.")
    appendLine("package ${d.packageName}")
    appendLine()
    appendLine("import center.tabula.Cell")
    appendLine("import center.tabula.Payloads")
    appendLine("import center.tabula.Step")
    appendLine("import center.tabula.Table")
    appendLine()

    appendLine("/**")
    appendLine(" * The cell surface: one required member per non-static cell, with narrowed")
    appendLine(" * argument types.")
    appendLine(" *")
    appendLine(" * An interface, not abstract members on a class, because this is what")
    appendLine(" * composes: a class extends one parent, so abstract members would cap")
    appendLine(" * composition at a single child. Interfaces are Kotlin's trait bounds.")
    appendLine(" */")
    val supers = d.children.joinToString("") { " ${it.packageName}.Cells," }
    appendLine("${vis}interface Cells${if (supers.isEmpty()) "" else " :${supers.dropLast(1)}"} {")

    forEachCell(d) { i, j, cell ->
        when (cell) {
            is CellDesc.Handle -> appendLine(
                "    ${mods}fun $recv${member(d, i, j)}(ctx: ${d.ctxType}, " +
                    "state: ${d.stateType}.${d.states[i].name}, " +
                    "action: ${d.actionType}.${d.actions[j].name}): Step<${d.stateType}, ${d.effectType}>"
            )
            is CellDesc.Delegate -> {
                val c = child(d, cell.child)
                appendLine(
                    "    ${mods}fun ${member(d, i, j)}ToChild(ctx: ${d.ctxType}, " +
                        "state: ${d.stateType}.${d.states[i].name}, " +
                        "action: ${d.actionType}.${d.actions[j].name}): ${c.packageName}.${c.actionType}?"
                )
            }
            else -> {}
        }
    }

    for (c in d.children) {
        appendLine()
        appendLine("    // Lens onto `${c.alias}`. Per child, not per cell.")
        val p = c.packageName
        appendLine("    fun ${c.alias}ChildState(state: ${d.stateType}): $p.${c.stateType}")
        appendLine("    fun ${c.alias}Embed(state: ${d.stateType}, child: $p.${c.stateType}): ${d.stateType}")
        appendLine("    fun ${c.alias}Lift(effect: $p.${c.effectType}): ${d.effectType}")
        appendLine("    fun ${c.alias}ChildCtx(ctx: ${d.ctxType}): $p.${c.ctxType}")
    }

    if (d.effects.isNotEmpty()) {
        appendLine()
        appendLine("    // One required member per effect variant. Add an effect and every")
        appendLine("    // handler stops compiling.")
        for (e in d.effects) {
            appendLine(
                "    ${mods}fun $recv${lower(e.name)}(ctx: ${d.ctxType}, " +
                    "effect: ${d.effectType}.${e.name}): ${d.actionType}?"
            )
        }
    }
    appendLine("}")
    appendLine()

    appendLine("/** Dispatch one `(state, action)` pair. No wildcard branch. */")
    appendLine(
        "$vis${mods}fun ${recv}step(cells: Cells, ctx: ${d.ctxType}, s: ${d.stateType}, a: ${d.actionType}): " +
            "Step<${d.stateType}, ${d.effectType}> = when (s) {"
    )
    d.states.forEachIndexed { i, state ->
        appendLine("    is ${d.stateType}.${state.name} -> when (a) {")
        d.actions.forEachIndexed { j, action ->
            appendLine("        is ${d.actionType}.${action.name} -> ${arm(d, i, j)}")
        }
        appendLine("    }")
    }
    appendLine("}")

    for (c in d.children) {
        appendLine()
        appendLine("/**")
        appendLine(" * Run `${c.alias}` and fold the result back through the lens.")
        appendLine(" *")
        appendLine(" * A null child action reports **Ignored**, not Stay: a parent action the")
        appendLine(" * child's alphabet does not contain was not handled.")
        appendLine(" */")
        appendLine(
            "private ${mods}fun delegateTo${cap(c.alias)}(cells: Cells, ctx: ${d.ctxType}, " +
                "s: ${d.stateType}, childAction: ${c.packageName}.${c.actionType}?): " +
                "Step<${d.stateType}, ${d.effectType}> {"
        )
        appendLine("    if (childAction == null) return Step.Ignored")
        appendLine("    val childStep = ${c.packageName}.step(")
        appendLine("        cells, cells.${c.alias}ChildCtx(ctx), cells.${c.alias}ChildState(s), childAction,")
        appendLine("    )")
        appendLine("    val effects = childStep.effects.map(cells::${c.alias}Lift)")
        appendLine("    return when (childStep) {")
        appendLine("        is Step.Go -> Step.Go(cells.${c.alias}Embed(s, childStep.next), effects)")
        appendLine("        is Step.Stay -> Step.Stay(effects)")
        appendLine("        is Step.Ignored -> Step.Ignored")
        appendLine("    }")
        appendLine("}")
    }

    if (d.effects.isNotEmpty()) {
        appendLine()
        appendLine("/** Carry out one effect, returning any follow-up action. */")
        appendLine(
            "$vis${mods}fun ${recv}perform(cells: Cells, ctx: ${d.ctxType}, f: ${d.effectType}): " +
                "${d.actionType}? = when (f) {"
        )
        for (e in d.effects) {
            appendLine("    is ${d.effectType}.${e.name} -> ${onCells(d, "${lower(e.name)}(ctx, f)")}")
        }
        appendLine("}")
    }

    d.render?.let { r ->
        val rmods = if (r.modifiers.isEmpty()) "" else r.modifiers.joinToString(" ") + " "
        appendLine()
        appendLine("/**")
        appendLine(" * The rendering surface: one required member per state, the state narrowed.")
        appendLine(" *")
        appendLine(" * Its own prototype and its own color. A `@Composable` belongs here, where a")
        appendLine(" * recomposition may call a member any number of times, and never reaches a")
        appendLine(" * transition. Add a state and every renderer stops compiling, as every")
        appendLine(" * handler does when a cell appears.")
        appendLine(" */")
        appendLine("${vis}interface Renders {")
        for (s in d.states) {
            appendLine("    ${rmods}fun render${cap(s.name)}(state: ${d.stateType}.${s.name}): ${r.returnType}")
        }
        appendLine("}")
        appendLine()
        appendLine("/** Render one state. No wildcard branch. */")
        appendLine(
            "$vis${rmods}fun render(renders: Renders, state: ${d.stateType}): ${r.returnType} = " +
                "when (state) {"
        )
        for (s in d.states) {
            appendLine("    is ${d.stateType}.${s.name} -> renders.render${cap(s.name)}(state)")
        }
        appendLine("}")
    }

    for (h in d.hops) hop(d, h, vis, mods, recv)

    appendLine()
    appendLine("/** The matrix as inert data. Diagrams, lints, and coverage read this. */")
    appendLine("${vis}val TABLE = Table(")
    appendLine("    machine = ${q(d.machine)},")
    appendLine("    states = listOf(${d.states.joinToString(", ") { q(it.name) }}),")
    appendLine("    actions = listOf(${d.actions.joinToString(", ") { q(it.name) }}),")
    appendLine("    initial = ${q(d.initial)},")
    appendLine("    cells = listOf(")
    d.rows.forEach { row ->
        appendLine("        listOf(${row.joinToString(", ") { cellData(it) }}),")
    }
    appendLine("    ),")
    appendLine(")")

    appendLine()
    appendLine("/** State payload fields, as `(state, field, type)`. */")
    val payloadStates = d.states.filter { it.hasPayload }
    if (payloadStates.isEmpty()) {
        appendLine("${vis}val PAYLOADS: Payloads = emptyList()")
    } else {
        appendLine("${vis}val PAYLOADS: Payloads = listOf(")
        for (v in payloadStates) {
            for ((f, t) in v.fields) {
                appendLine("    Triple(${q(v.name)}, ${q(f)}, ${q(t)}),")
            }
        }
        appendLine(")")
    }
}

private inline fun forEachCell(d: MachineDesc, body: (Int, Int, CellDesc) -> Unit) {
    d.rows.forEachIndexed { i, row -> row.forEachIndexed { j, c -> body(i, j, c) } }
}

internal fun hopOutcomes(d: MachineDesc, h: HopDesc): List<Int> {
    val out = sortedSetOf(h.to)
    for (cell in d.rows[h.from]) {
        when (cell) {
            is CellDesc.Go -> out += d.states.indexOfFirst { it.name == cell.target }
            is CellDesc.Emit, CellDesc.Ignore, is CellDesc.Delegate -> out += h.from
            CellDesc.Handle -> out += d.states.indices
            CellDesc.Unreachable -> {}
        }
    }
    return out.toList()
}

private fun StringBuilder.hop(d: MachineDesc, h: HopDesc, vis: String, mods: String, recv: String) {
    val name = member(d, h.from, h.action)
    val type = cap(name)
    val st = d.stateType
    val from = d.states[h.from].name
    val to = d.states[h.to].name
    val outcomes = hopOutcomes(d, h)
    val others = outcomes.filter { it != h.to }

    appendLine()
    appendLine("/**")
    appendLine(" * Where `$from` can go when an action arrives, on the path through")
    appendLine(" * `$from -${d.actions[h.action].name}-> $to`: `$to` is the happy outcome, the rest are")
    appendLine(" * what else the `$from` row can produce. Each carries the step's effects.")
    appendLine(" */")
    appendLine("${vis}sealed class $type {")
    appendLine("    abstract val effects: List<${d.effectType}>")
    for (i in outcomes) {
        val s = d.states[i].name
        appendLine("    data class $s(val state: $st.$s, override val effects: List<${d.effectType}>) : $type()")
    }
    appendLine("}")

    val self = if (recv.isEmpty()) "Cells." else recv
    val cellsParam = if (recv.isEmpty()) "" else "cells: Cells, "
    val cellsArg = if (recv.isEmpty()) "this" else "cells"
    appendLine()
    appendLine("/** `$from` receives [action]; the matrix decides the outcome. Effects come back, never run. */")
    appendLine(
        "$vis${mods}fun $self$name(${cellsParam}ctx: ${d.ctxType}, state: $st.$from, action: ${d.actionType}): " +
            "$type {"
    )
    appendLine("    val s = step($cellsArg, ctx, state, action)")
    appendLine("    val next: $st = when (s) {")
    appendLine("        is Step.Go -> s.next")
    appendLine("        is Step.Stay -> state")
    appendLine("        is Step.Ignored -> state")
    appendLine("    }")
    appendLine("    return when (next) {")
    for ((i, v) in d.states.withIndex()) {
        if (i in outcomes) {
            appendLine("        is $st.${v.name} -> $type.${v.name}(next, s.effects)")
        } else {
            appendLine("        is $st.${v.name} -> error(\"tabular-center: the `$from` row cannot produce `${v.name}`\")")
        }
    }
    appendLine("    }")
    appendLine("}")

    appendLine()
    appendLine("/** The happy outcome of [$name], or each handler's answer for the others. */")
    if (others.isEmpty()) {
        appendLine("${vis}inline fun $type.elvis(): $type.$to = when (this) {")
    } else {
        val infix = if (others.size == 1) "infix " else ""
        appendLine("${vis}inline ${infix}fun $type.elvis(")
        for (i in others) {
            val s = d.states[i].name
            appendLine("    $s: ($type.$s) -> $type.$to,")
        }
        appendLine("): $type.$to = when (this) {")
    }
    appendLine("    is $type.$to -> this")
    for (i in others) {
        val s = d.states[i].name
        appendLine("    is $type.$s -> $s(this)")
    }
    appendLine("}")
}

/**
 * One member of the generated `Cells` interface, and what it was generated
 * from -- for `tabular-center::member-collision`.
 */
internal data class GeneratedMember(val name: String, val origin: String, val state: String?)

internal fun cellsMembers(d: MachineDesc): List<GeneratedMember> = buildList {
    forEachCell(d) { i, j, cell ->
        val at = "cell (${d.states[i].name}, ${d.actions[j].name})"
        when (cell) {
            is CellDesc.Handle -> add(GeneratedMember(member(d, i, j), at, d.states[i].name))
            is CellDesc.Delegate ->
                add(GeneratedMember(member(d, i, j) + "ToChild", at, d.states[i].name))
            else -> {}
        }
    }
    for (c in d.children) {
        for (suffix in listOf("ChildState", "Embed", "Lift", "ChildCtx")) {
            add(GeneratedMember(c.alias + suffix, "child `${c.alias}`", null))
        }
    }
    for (e in d.effects) add(GeneratedMember(lower(e.name), "effect ${e.name}", null))
    for (h in d.hops) {
        val at = "hop (${d.states[h.from].name}, ${d.actions[h.action].name})"
        add(GeneratedMember(member(d, h.from, h.action), at, d.states[h.from].name))
    }
}

private fun child(d: MachineDesc, alias: String): ChildDesc =
    d.children.firstOrNull { it.alias == alias }
        ?: error("tabular-center::unknown-child: `$alias` is not a declared child")

private fun member(d: MachineDesc, i: Int, j: Int): String =
    lower(d.states[i].name) + cap(d.actions[j].name)

private fun arm(d: MachineDesc, i: Int, j: Int): String {
    val bind = if (d.states[i].hasPayload || d.actions[j].hasPayload) "s, a" else "s, a"
    return when (val c = d.rows[i][j]) {
        is CellDesc.Ignore -> "Step.Ignored"
        is CellDesc.Handle -> onCells(d, "${member(d, i, j)}(ctx, $bind)")
        is CellDesc.Unreachable ->
            "error(${q("tabular-center: ${d.states[i].name} x ${d.actions[j].name} was declared UNREACHABLE but occurred")})"
        is CellDesc.Go -> {
            val target = "${d.stateType}.${c.target}${c.targetArgs}"
            if (c.effects.isEmpty()) "Step.Go($target)"
            else "Step.Go($target, listOf(${c.effects.joinToString(", ") { "${d.effectType}.$it" }}))"
        }
        is CellDesc.Emit ->
            "Step.Stay(listOf(${c.effects.joinToString(", ") { "${d.effectType}.$it" }}))"
        is CellDesc.Delegate ->
            "delegateTo${cap(c.child)}(cells, ctx, s, cells.${member(d, i, j)}ToChild(ctx, s, a))"
    }
}

private fun onCells(d: MachineDesc, call: String): String =
    if (d.prototypeReceiver.isEmpty()) "cells.$call" else "with(cells) { $call }"

private fun cellData(c: CellDesc): String = when (c) {
    is CellDesc.Ignore -> "Cell.Ignore"
    is CellDesc.Handle -> "Cell.Handle"
    is CellDesc.Unreachable -> "Cell.Unreachable"
    is CellDesc.Go ->
        if (c.effects.isEmpty()) "Cell.Go(${q(c.target)})"
        else "Cell.Go(${q(c.target)}, listOf(${c.effects.joinToString(", ") { q(effectName(it)) }}))"
    is CellDesc.Emit -> "Cell.Emit(listOf(${c.effects.joinToString(", ") { q(effectName(it)) }}))"
    is CellDesc.Delegate -> "Cell.Delegate(${q(c.child)})"
}

private fun q(s: String) = "\"$s\""
private fun lower(s: String) = s.replaceFirstChar { it.lowercase() }
private fun cap(s: String) = s.replaceFirstChar { it.uppercase() }
